namespace CaixaDiario.API.Enums;

public enum CodigoRetorno
{
    SUCESSO,
    DADOS_INVALIDOS,
    CREDENCIAIS_INVALIDAS,
    USUARIO_INATIVO,
    TOKEN_INVALIDO,
    SEM_PERMISSAO,
    SENHA_MUITO_CURTA,
    USUARIO_NAO_ENCONTRADO,
    NOME_USUARIO_DUPLICADO,
    DATA_FUTURA,
    MOTIVO_OBRIGATORIO,
    REGISTRO_NAO_ENCONTRADO,
    ACESSO_NEGADO,
    META_NAO_ENCONTRADA,
    ERRO_INTERNO,
    CONTA_RECORRENTE_NAO_ENCONTRADA = 15,
    CATEGORIA_NAO_ENCONTRADA,
    CATEGORIA_DUPLICADA,
    CATEGORIA_EM_USO,
    TRANSFERENCIA_NAO_ENCONTRADA,
    CONTA_INATIVA
}
