// <auto-generated />
using System;
using CaixaDiario.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CaixaDiario.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624200000_AdicionarTransacoesImportadas")]
    partial class AdicionarTransacoesImportadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Mantido vazio intencionalmente.
            // Use `dotnet ef migrations add` para regenerar o snapshot completo.
        }
    }
}
