// <auto-generated />
using System;
using CaixaDiario.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CaixaDiario.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624230000_AdicionarMetaSonhoExtensao")]
    partial class AdicionarMetaSonhoExtensao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Mantido vazio intencionalmente.
        }
    }
}
