// <auto-generated />
using System;
using CaixaDiario.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaixaDiario.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624125600_AdicionarContasBancarias")]
    partial class AdicionarContasBancarias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaixaDiario.API.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcaoTipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acao_tipo");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("DadosAntes")
                        .HasColumnType("text")
                        .HasColumnName("dados_antes");

                    b.Property<string>("DadosDepois")
                        .HasColumnType("text")
                        .HasColumnName("dados_depois");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidade");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidade_id");

                    b.Property<DateTime>("OcorridoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "OcorridoEm");

                    b.HasIndex("Entidade", "AcaoTipo");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CaixaDiario.API.Models.ContaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal>("SaldoInicial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("saldo_inicial");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Caixa")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Ativa");

                    b.ToTable("contas_bancarias", (string)null);
                });

            modelBuilder.Entity("CaixaDiario.API.Models.ContaRecorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Periodicidade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Mensal")
                        .HasColumnName("periodicidade");

                    b.Property<int?>("QuantidadeParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Ativo");

                    b.ToTable("contas_recorrentes", (string)null);
                });

            modelBuilder.Entity("CaixaDiario.API.Models.MetaAnual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("MesInicio")
                        .HasColumnType("integer");

                    b.Property<decimal>("MetaLucro")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("meta_lucro");

                    b.Property<decimal>("MetaReceita")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("meta_receita");

                    b.Property<string>("ModoMeta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PeriodoMeses")
                        .HasColumnType("integer");

                    b.Property<int>("PrazoAnos")
                        .HasColumnType("integer");

                    b.Property<string>("Sonho")
                        .HasColumnType("text");

                    b.Property<decimal>("TaxaRetorno")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalInvestido")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorSonho")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Ano")
                        .IsUnique();

                    b.ToTable("metas_anuais", (string)null);
                });

            modelBuilder.Entity("CaixaDiario.API.Models.RegistroDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<Guid?>("ContaBancariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_bancaria_id");

                    b.Property<string>("ContasPagar")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contas_pagar");

                    b.Property<string>("ContasReceber")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contas_receber");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Entradas")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("entradas");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<decimal>("Inicio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("inicio");

                    b.Property<string>("MotivoExclusao")
                        .HasColumnType("text")
                        .HasColumnName("motivo_exclusao");

                    b.Property<string>("Saidas")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("saidas");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_final");

                    b.Property<DateTime>("SalvoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("salvo_em");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text")
                        .HasColumnName("usuario_atualizacao");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Data");

                    b.HasIndex("ContaBancariaId", "Data")
                        .IsUnique()
                        .HasFilter("conta_bancaria_id IS NOT NULL AND excluido = FALSE");

                    b.ToTable("registros_diarios", (string)null);
                });

            modelBuilder.Entity("CaixaDiario.API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Loja")
                        .HasColumnType("text")
                        .HasColumnName("loja");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text")
                        .HasColumnName("usuario_atualizacao");

                    b.HasKey("Id");

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("CaixaDiario.API.Models.ContaBancaria", b =>
                {
                    b.HasOne("CaixaDiario.API.Models.Usuario", "Cliente")
                        .WithMany("ContasBancarias")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CaixaDiario.API.Models.ContaRecorrente", b =>
                {
                    b.HasOne("CaixaDiario.API.Models.Usuario", "Cliente")
                        .WithMany("ContasRecorrentes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CaixaDiario.API.Models.MetaAnual", b =>
                {
                    b.HasOne("CaixaDiario.API.Models.Usuario", "Cliente")
                        .WithMany("MetasAnuais")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CaixaDiario.API.Models.RegistroDiario", b =>
                {
                    b.HasOne("CaixaDiario.API.Models.Usuario", "Cliente")
                        .WithMany("Registros")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaixaDiario.API.Models.ContaBancaria", "ContaBancaria")
                        .WithMany("Registros")
                        .HasForeignKey("ContaBancariaId");

                    b.Navigation("Cliente");

                    b.Navigation("ContaBancaria");
                });

            modelBuilder.Entity("CaixaDiario.API.Models.ContaBancaria", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("CaixaDiario.API.Models.Usuario", b =>
                {
                    b.Navigation("ContasBancarias");

                    b.Navigation("ContasRecorrentes");

                    b.Navigation("MetasAnuais");

                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
